/**
 * Turns "Molit." into vector paths from the bundled Geist Bold font so the
 * lockup is exact geometry, not CSS line-box maths. Writes
 * src/components/wordmark-paths.ts. Re-run if the font or tracking changes.
 *
 *   npx tsx scripts/build-wordmark.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import opentype from "opentype.js";

const FONT = "src/assets/fonts/Geist-Bold.woff";
const TRACKING = -0.045; // em, matches the CSS wordmark

const buf = readFileSync(join(process.cwd(), FONT));
const font = opentype.parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength));
const upm = font.unitsPerEm;
const size = 1000; // work in a 1000-unit em
const scale = size / upm;

const capTop = font.charToGlyph("l").getBoundingBox().y2 * scale; // ascender of "l" (= cap height in Geist)
const xHeight = font.charToGlyph("x").getBoundingBox().y2 * scale;

function layout(text: string, x0: number) {
  const glyphs = font.stringToGlyphs(text);
  let x = x0;
  let d = "";
  for (let i = 0; i < glyphs.length; i++) {
    const g = glyphs[i];
    // y flipped: baseline at y = capTop, ascender at y = 0
    const p = g.getPath(x, capTop, size);
    d += p.toPathData(2);
    let adv = (g.advanceWidth ?? 0) * scale;
    if (i < glyphs.length - 1) adv += font.getKerningValue(g, glyphs[i + 1]) * scale;
    adv += TRACKING * size;
    x += adv;
  }
  return { d, end: x };
}

const word = layout("Molit", 0);
const dotGlyph = font.charToGlyph(".");
const dotStart = word.end;
const dot = layout(".", dotStart);
const dotAdvance = (dotGlyph.advanceWidth ?? 0) * scale;
const inkRight = dotGlyph.getBoundingBox().x2 * scale + dotStart;
const inkLeft = font.charToGlyph("M").getBoundingBox().x1 * scale;

const out = `// Generated by scripts/build-wordmark.ts from ${FONT}. Do not edit by hand.
// Coordinate system: 1000 units per em, y down, ascender of "l" at y=0, baseline at y=${capTop.toFixed(1)}.
export const WORDMARK = {
  capTop: ${capTop.toFixed(1)},
  xHeight: ${xHeight.toFixed(1)},
  inkLeft: ${inkLeft.toFixed(1)},
  inkRight: ${inkRight.toFixed(1)},
  dotAdvance: ${dotAdvance.toFixed(1)},
  word: ${JSON.stringify(word.d)},
  dot: ${JSON.stringify(dot.d)},
} as const;
`;
writeFileSync(join(process.cwd(), "src/components/wordmark-paths.ts"), out);
console.log(`capTop ${capTop.toFixed(1)}  xHeight ${xHeight.toFixed(1)}  ink ${inkLeft.toFixed(1)}..${inkRight.toFixed(1)}  dot ${dotAdvance.toFixed(1)}`);
